### ISSUE TITLE
Application doesn't open after closing it with the following issue

### ISSUE THREAD

**Issue by violog** [sgpthomas/hourglass#112]
Sometimes, after closing the app I can't launch it via icon: nothing happens. When launching from terminal (both app and it's daemon from /usr/bin), it shows an error:

`** (com.github.sgpthomas.hourglass-daemon:9614): CRITICAL **: 12:53:41.301: HourglassServer.vala:78: Could not aquire service name`

There is also running process of hourglass. When I kill it, I can normally start the app.
OS Arch Linux, Kernel 5.11.16-arch1-1.

**Comment by JayXT** [comment]
Yes, I've had the same issue.

**Comment by ryonakano** [comment]
Should be fixed with the latest release 1.4.0 for Odin.
