### ISSUE TITLE
AppData summary is too verbose

### ISSUE THREAD

**Issue by danrabbit** [sgpthomas/hourglass#180]
https://github.com/sgpthomas/hourglass/blob/446f4a36b807521cf077dfc3734b10d36d06e8e3/data/com.github.sgpthomas.hourglass.appdata.xml.in#L9

The summary contains superfluous descriptions and in some views that means the most important parts of the summary are cut off:

![Screenshot from 2021-11-07 15 11 27](https://user-images.githubusercontent.com/7277719/140665512-06a87cfe-1365-42cb-95a6-e3e6cb7c2281.png)

Consider getting to the point much faster:

![Screenshot from 2021-11-07 15 14 02](https://user-images.githubusercontent.com/7277719/140665511-62fe1c67-8f94-4dcb-902b-6a81e0840851.png)

**Comment by ryonakano** [comment]
Fixed in c72d974, I decided to match this text with the Comment field in the desktop file. Thank you for your suggestion!
