### ISSUE TITLE
Flagged Out Of Date AUR Packages: hourglass

### ISSUE THREAD

**Issue by mouhsineelachbi** [sgpthomas/hourglass#242]
Hello,

I'm using yay in archlinux to update packages and everytime I get this message saying that hourglass is flagged out of date
` -> Flagged Out Of Date AUR Packages: hourglass`

I'm using version Version : 2.0.2-1
My kernel version : 6.8.9-arch1-2

**Comment by ryonakano** [comment]
I don't maintain AUR packages of Hourglass, but the following one looks maintained actively. Does it work for you?

https://aur.archlinux.org/packages/hourglass-git

**Comment by ryonakano** [comment]
Closing since there is an alternative package as mentioned above.
