### ISSUE TITLE
Repeat label is a bit close to the alarm time

### ISSUE THREAD

**Issue by cassidyjames** [sgpthomas/hourglass#29]
Pics are worth 1000 words
![hourglass-alarm](https://cloud.githubusercontent.com/assets/611168/25734606/fcf6e842-3121-11e7-9456-d2047ad5d5a4.png)

**Comment by sgpthomas** [comment]
Been meaning to fix that for a while. Should take a few seconds. Do you think it should go in the middle? Or just have some padding?

**Comment by cassidyjames** [comment]
Hm, I think either would work. Centering would start to look weird on pretty wide windows, though, so maybe just do a margin-left of about 12px?
