### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by sgpthomas** [sgpthomas/hourglass#32]

**Comment by ryonakano** [comment]
I don't know what you want to update specifically, but I think we might want to add the following things at least:

* App screenshot(s)
* Dependencies and how to build the app (this is in the `INSTALL` file at the moment)

**Comment by ryonakano** [comment]
@sgpthomas App screenshots and dependencies list is now added, is there anything else you want to add to README?

**Comment by sgpthomas** [comment]
I think this looks good! I'll close the issue.
