### ISSUE TITLE
timekeeping

### ISSUE THREAD

**Issue by lecroix74** [sgpthomas/hourglass#34]
has anyone else noticed, that the time keeping in this app is wrong? 55second shown in this app is in reality one whole minute. so 5 real minutes is indicated as 4min25sec in Hourglass! how the hell is this possible???
I hope this will be taken off the AppCentre. just horrible.

**Comment by peteruithoven** [comment]
Let's stay friendly. Someone put time and energy into this and shared it, for free. 

Where did  you notice this? In which tab (Alarm / Stopwatch / Timer)? What did you do to see this?

**Comment by sgpthomas** [comment]
I figured out the problem. The way I do timing is probably based on CPU cycles rather than precise time. I'll work on fixing this

**Comment by lecroix74** [comment]
It happens in Timer and Stopwatch. I did not check how it affects Alarm.
I found out about this by pure chance when I started another stopwatch to run along side Hourglass.

**Comment by lecroix74** [comment]
after all this time the thread has been closed and not solved? what a pity. if every app is maintained like this, the whole idea of apps should be binned. let's just download GNOME apps with certainty of proper maintenance

**Comment by sgpthomas** [comment]
this is fixed, which is why I closed it I haven't released the fix yet. if you want to test it you have to compile it yourself.
