### ISSUE TITLE
Persistent Notification through indicator-messages ?

### ISSUE THREAD

**Issue by khurshid-alam** [sgpthomas/hourglass#42]
As of now if user misses a notification, there is no way to get it back. . Both Elementary and Unity uses indicator-messages. It would be nice if hourglass can integrate with that. It would also help other DE (like Mate, Solus) to integrate with desktop better.

**Workflow:**

A) When timer's time elapses, it creates a simple notification in the indicator. And indicator-messeges turns blue.

B) When user click the message it simply bring app in focus. The notifications from indicators are removed automatically.

Messeging-Menu API:

https://developer.ubuntu.com/api/devel/ubuntu-13.10/python/MessagingMenu-1.0.html#MessagingMenu.Message

A simple example:

http://bazaar.launchpad.net/~indicator-applet-developers/indicator-messages/trunk.16.10/view/head:/libmessaging-menu/client-example.py

**Comment by khurshid-alam** [comment]
@sgpthomas ?

**Comment by sgpthomas** [comment]
that's a good idea, I've been super busy with school recently. I'll work on this next weekend

**Comment by khurshid-alam** [comment]
Any news on this?

**Comment by sgpthomas** [comment]
are you referring to the notifications menu? I don't think elementary ships with the messaging menu anymore. What version are you on? I should be able to create a very similar effect with the notifications menu though

**Comment by khurshid-alam** [comment]
@sgpthomas 
Yes Notification-menu.But it uses messaging-menu api. This is what I meant:
![](https://www.linux.com/sites/lcom/files/styles/rendered_file/public/loki_a.png?itok=q3VZoRbf)

**Comment by sgpthomas** [comment]
I couldn't find anything about the messaging-menu api in Vala nowadays, but I do know how to do the same thing using GLib.Notification. I'm ironing out some more critical bugs now, and then I'll work on this.

**Comment by khurshid-alam** [comment]
@sgpthomas 
You can look at wingpanel indicator notification api and also here: https://github.com/elementary/wingpanel-indicator-notifications/blob/master/src/Indicator.vala

**Comment by ryonakano** [comment]
Pantheon no longer uses indicator-messages; it's for Unity. So closing this issue.
