### ISSUE TITLE
Hourglass creates duplicate alarm after editing the alarm

### ISSUE THREAD

**Issue by khurshid-alam** [sgpthomas/hourglass#44]
How to reproduce:

1) Add a alarm
2) Edit it & set a different time. It will create a new alarm with same name. Close Hourglass gui.
3) Wait until it's fired. Open Hourglass.
4) You will see a duplicate of original alarm along with the new alarm.

Version: git+master

**Comment by ryonakano** [comment]
Thank you for reporting, but I can't seem to reproduce this issue now. Closing.
