### ISSUE TITLE
Publish in Juno

### ISSUE THREAD

**Issue by danrabbit** [sgpthomas/hourglass#50]
Our [second Juno Developer Preview](https://medium.com/elementaryos/developer-preview-juno-beta-2-is-out-418f5037e9bb) is out and Juno's big debut is just around the corner! We'd love to see your app in AppCenter on release day.

Check out this [Developer Tips](https://medium.com/elementaryos/developer-tips-updating-your-apps-for-juno-453c07a5b3a7) article to learn how to publish your app for elementary OS 5.

If you need help updating your app for Juno, we’re always standing by in [Gitter](https://gitter.im/elementary/houston) and the [Community Slack](https://join.slack.com/t/elementarycommunity/shared_invite/enQtMzU1NDU4OTE1MjY2LWUyOTBkZGNkZGM4MDgzZjE2ZjRiZDgwMDQ1ZTA0MzcxYjI0MDUyNGRlNDI5ZWViNDkwMzMwYzczMDY2ZjA0MTc) to help wherever we can.

**Comment by ryonakano** [comment]
@sgpthomas Is there any plan to publish this app to AppCenter again?

**Comment by sgpthomas** [comment]
Not anytime soon because I'm very busy with school and I don't have time to properly maintain it :(

I would be happy to help somebody else pick it up though.

**Comment by ryonakano** [comment]
@sgpthomas All right, it does not need to be immediate, it's fine when you get free.

IIRC When I tried to build and use this app in Juno, it successfully built, although it outputs some error messages. So I think just creating a new release on GitHub and submitting it in the AppCenter Dashboard should publish the app to Juno.

But I guess we also need to keep it up-to-date as possible. For example, elementary [announced](https://medium.com/elementaryos/all-aboard-the-meson-future-hype-train-2b6c478b6b9e) that they'll migrate the build system from CMake to Meson last January and many official apps and third-party apps are updated to use Meson. Although releasing apps with CMake to AppCenter is still supported, but at some time it might be dropped. So I've created a PR to update the building system of this app from CMake to Meson (see #53).

I can help you anytime if you need it. :relaxed:

**Comment by hacebe** [comment]
Hi @ryonakano ,

How can I apply your patch and compile it myself? The current version is not working properly when I add an alarm. Maybe with your patch it would be solved. I appreciate your help and I find this app really useful for me! 

I got this error when trying to create an alarm:
`file /home/hacebe/Downloads/hourglass/src/Widgets/AlarmTimeWidget.vala: line 196: uncaught error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.github.sgpthomas.hourglass was not provided by any .service files (g-dbus-error-quark, 2)`

**Comment by ryonakano** [comment]
Hello @hacebe,
Unfortunately, my patch does not fix that bug. My patch (#53) just changes build systems and does not change app behavior at all. So I've also confirmed that issue on my side too. I've filed a new issue for that.

**Comment by sgpthomas** [comment]
@ryonakano @hacebe Hey, I'm sorry that I have abandoned this project. Because I don't anticipate picking it up again anytime soon, I would be happy to transfer the ownership of the repo to one of you so you that guys can maintain it. If you are interested, let me know!

**Comment by ryonakano** [comment]
@sgpthomas In case you are busy and can't release a new version, I'd like to do it instead of you if you would add me as a Collaborator :)
