### ISSUE TITLE
Left time shows unexpected values if set time is too big

### ISSUE THREAD

**Issue by Fatih20** [sgpthomas/hourglass#86]
The timer apparently goes off instantly when they are set to a certain value and doesn't go at the right time in another value? I can't really explain it, here's a video of me showing it.
https://open.lbry.com/Screen-record-from-2020-06-25-09.14.28:c?r=3r6R1wGsDKz76CrjA43SEhst8E9TKcgZ

**Comment by ryonakano** [comment]
I can confirm this issue when I try to count down 11 min 36 hours or more.
