### ISSUE TITLE
Stopwatch laps hard to read

### ISSUE THREAD

**Issue by cassidyjames** [sgpthomas/hourglass#96]
1.2.2 from AppCenter

![image](https://user-images.githubusercontent.com/611168/93149127-c9e41100-f6b2-11ea-9c26-c615f377456b.png)

**Comment by ryonakano** [comment]
Closing as a duplicate of #55. I'll take a look at this soon :eyes:

**Comment by cassidyjames** [comment]
Ah, my bad! I thought this was a new issue with 1.2.2 so I didn't even search for duplicates. :facepalm:
